export const productList = [
  {
    id: 1,
    code: 850,
    category: "פיצות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "פיצה מרגריטה",
    alt: "תמונה 1",
    description: "פיצה קלאסית עם רוטב עגבניות וגבינה מוזרלה",
    price: 38.5,
  },
  {
    id: 2,
    code: 851,
    category: "פיצות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "פיצה פפרוני",
    alt: "תמונה 2",
    description: "פיצה עם פלפלים מתוקים, פלפל חריף, זיתים וגבינה מוזרלה",
    price: 42.9,
  },
  {
    id: 3,
    code: 852,
    category: "פיצות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "פיצה פירורי דג",
    alt: "תמונה 3",
    description: "פיצה עם פירורי דג, קרם עגבניות ושמן זית",
    price: 46.5,
  },
  {
    id: 4,
    code: 858,
    category: "טוסטים",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "טוסט עם פרוסות אבוקדו",
    alt: "תמונה 8",
    description: "טוסט עם פרוסות אבוקדו ורוטב צ'ילי",
    price: 24.9,
  },
  {
    id: 5,
    code: 859,
    category: "טוסטים",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "טוסט עם קממבר ובצל ירוק",
    alt: "תמונה 9",
    description: "טוסט עם קממבר, בצל ירוק ורוטב ברביקיו",
    price: 28.5,
  },
  {
    id: 6,
    code: 860,
    category: "זיוות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "זיווט בשרי",
    alt: "תמונה 10",
    description: "שניצל משוגע עם תפוח אדמה מטוגן ורוטב חריף",
    price: 42.9,
  },
  {
    id: 7,
    code: 861,
    category: "זיוות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "זיווט צמחוני",
    alt: "תמונה 11",
    description: "מבחר ירקות צלויים עם תפוח אדמה מטוגן ורוטב פיקנטי",
    price: 38.5,
  },
  {
    id: 7,
    code: 861,
    category: "סלטים",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "זיווט צמחוני",
    alt: "תמונה 11",
    description: "מבחר ירקות צלויים עם תפוח אדמה מטוגן ורוטב פיקנטי",
    price: 38.5,
  },
];

export const productCategories = [
  ...new Set(productList.map((product) => product.category)),
];

export const productSortOptions = [
  { _id: `1`, name: `category`, content: `קטגוריה` },
  { _id: `2`, name: `lowPrice`, content: `מחיר נמוך לגבוה` },
  { _id: `3`, name: `highPrice`, content: `מחיר גבוה לנמוך` },
];
