export const productList = [
  {
    _id: `1`,
    code: 850,
    category: "פיצות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "פיצה מרגריטה",
    alt: "תמונה 1",
    description: "פיצה קלאסית עם רוטב עגבניות וגבינה מוזרלה",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 38.5,
  },
  {
    _id: `2`,
    code: 851,
    category: "פיצות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "פיצה פפרוני",
    alt: "תמונה 2",
    description: "פיצה עם פלפלים מתוקים, פלפל חריף, זיתים וגבינה מוזרלה",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 42.9,
  },
  {
    _id: `3`,
    code: 852,
    category: "פיצות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "פיצה פירורי דג",
    alt: "תמונה 3",
    description: "פיצה עם פירורי דג, קרם עגבניות ושמן זית",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 46.5,
  },
  {
    _id: `4`,
    code: 858,
    category: "טוסטים",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "טוסט עם פרוסות אבוקדו",
    alt: "תמונה 8",
    description: "טוסט עם פרוסות אבוקדו ורוטב צ'ילי",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 24.9,
  },
  {
    _id: `5`,
    code: 859,
    category: "טוסטים",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "טוסט עם קממבר ובצל ירוק",
    alt: "תמונה 9",
    description: "טוסט עם קממבר, בצל ירוק ורוטב ברביקיו",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 28.5,
  },
  {
    _id: `6`,
    code: 860,
    category: "זיוות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "זיווט בשרי",
    alt: "תמונה 10",
    description: "שניצל משוגע עם תפוח אדמה מטוגן ורוטב חריף",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 42.9,
  },
  {
    _id: `7`,
    code: 861,
    category: "זיוות",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "זיווט צמחוני",
    alt: "תמונה 11",
    description: "מבחר ירקות צלויים עם תפוח אדמה מטוגן ורוטב פיקנטי",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 38.5,
  },
  {
    _id: `7`,
    code: 861,
    category: "סלטים",
    imageUrl: "/images/menu/burger-18.jpg",
    title: "זיווט צמחוני",
    alt: "תמונה 11",
    description: "מבחר ירקות צלויים עם תפוח אדמה מטוגן ורוטב פיקנטי",
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
    price: 38.5,
  },
  {
    _id: "8",
    category: `פיצות`,
    title: "פיצה עוף בופאלו",
    code: 1039,
    linkPath: "/product-single",
    imageUrl: "/images/menu/pizza-05.png",
    price: 11.99,
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
  },
  {
    _id: "9",
    category: `פיצות`,
    title: "פיצה פפרוני",
    code: 1040,
    linkPath: "/product-single",
    imageUrl: "/images/menu/pizza-06.png",
    price: 11.99,
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
  },
  {
    _id: "10",
    category: `פיצות`,
    title: "פיצה מרגריטה",
    code: 1041,
    linkPath: "/product-single",
    imageUrl: "/images/menu/pizza-07.png",
    price: 11.99,
    medium: { text: "משפחתית", price: 10.99 },
    large: { text: "ענקית", price: 15.99 },
  },
];

export const productCategories = [
  ...new Set(productList.map((product) => product.category)),
];

export const productSortOptions = [
  { _id: `1`, name: `category`, content: `קטגוריה` },
  { _id: `2`, name: `lowPrice`, content: `מחיר נמוך לגבוה` },
  { _id: `3`, name: `highPrice`, content: `מחיר גבוה לנמוך` },
];
